[theme]
primaryColor = "#238636"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E6EDF3"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false